POST https://node-do-0-yr0n.onrender.com/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "Este é o vídeo node",
    "duration": 180
}

###

GET https://node-do-0-yr0n.onrender.com/videos

###

PUT https://node-do-0-yr0n.onrender.com/videos/a85bcae8-a253-4f70-b642-6c75453c76b6
Content-Type: application/json

{
    "title": "video 02",
    "description": "Este é o vídeo 02",
    "duration": 180
}

###

DELETE  https://node-do-0-yr0n.onrender.com/videos/c9935be8-954a-458a-8b28-ed7602fad265
